// user Resducer type
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const UPDATE_DATA = 'UPDATE_DATA';

// UI Reducer
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_UI_LOADING = 'STOP_UI_LOADING';

// Customer
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const COMPLETE_PROJECT = 'CO9MPLETE_PROJECT';
export const CLOSE_PROJECT = 'CLOSE_PROJECT';

// Perposal
export const GET_PERPOSALS = 'GET_PERPOSALS';
export const GET_PERPOSAL = 'GET_PERPOSAL';
export const CREATE_PERPOSAL = 'CREATE_PERPOSAL';
export const DELETE_PERPOSAL = 'DELETE_PERPOSAL';
export const UPDATE_PERPOSAL = 'UPDATE_PERPOSAL';
export const PERPOSAL_ACTION = 'PERPOSAL_ACTION';
